import type { Metadata } from 'next';

import { SITE } from '@/config/site';
import { siteUrl } from '@/lib/env';

/**
 * One builder for every public page's metadata.
 *
 * The reason it exists is duplication of the wrong kind. Open Graph and
 * Twitter want the same title, description, canonical URL and image as the
 * page itself, expressed three times in three vocabularies, and a page that
 * spells all three out by hand will sooner or later have a description that
 * matches on the page and not in the share card. Everything is derived here
 * from one set of facts, so they cannot drift.
 *
 * What is NOT here is a default description. A page that forgets to pass one
 * gets no description tag rather than the site's boilerplate repeated across
 * forty pages, which is the duplicate metadata the brief asks us to avoid —
 * and which reads to a search engine as forty pages about nothing in
 * particular. Missing is honest and the audit at /admin/seo will find it.
 *
 * There is no Twitter/X handle in the site configuration, so `twitter.site`
 * and `twitter.creator` are not emitted. Inventing an @name that resolves to
 * somebody else's account is worse than omitting it.
 */

/** The share image every page falls back to, generated by `opengraph-image`. */
export const DEFAULT_OG_IMAGE = '/opengraph-image';

export interface PublicPageSeo {
  /** The page's own title, without the site name — the template adds it. */
  title: string;
  /** One or two sentences about THIS page. Omitted rather than invented. */
  description?: string;
  /** The canonical path, beginning with a slash. Never a full URL. */
  path: string;
  /** Absolute or site-relative image URLs. Falls back to the branded card. */
  images?: readonly string[];
  /** 'website' for a listing or landing page, 'article' for one advertisement. */
  type?: 'website' | 'article';
  /**
   * Whether search engines should index it. Default true; pass false for a
   * page that exists for people but has nothing to rank — an expired
   * advertisement, a filtered view, a half-finished form.
   */
  index?: boolean;
  /** Alternative text for the share image, for readers who cannot see it. */
  imageAlt?: string;
}

export function publicMetadata({
  title,
  description,
  path,
  images,
  type = 'website',
  index = true,
  imageAlt,
}: PublicPageSeo): Metadata {
  const base = siteUrl();
  const canonical = normalisePath(path);
  const url = `${base}${canonical === '/' ? '' : canonical}`;

  const resolved = (images?.length ? images : [DEFAULT_OG_IMAGE]).map((image) =>
    image.startsWith('http') ? image : `${base}${image}`,
  );

  // The share card carries the site name; the page's own <title> gets it from
  // the template in the root layout. Spelling it out in both would produce
  // "Jobs | Shree Classified | Shree Classified" in one of them.
  const shareTitle = `${title} | ${SITE.name}`;

  return {
    title,
    ...(description ? { description } : {}),
    alternates: { canonical },
    robots: index
      ? { index: true, follow: true }
      : // `follow` stays on so the links out of a page nobody should index —
        // an expired advertisement pointing at current ones — still carry
        // their value and still get crawled.
        { index: false, follow: true },
    openGraph: {
      type,
      title: shareTitle,
      ...(description ? { description } : {}),
      url,
      siteName: SITE.name,
      locale: 'en_IN',
      images: resolved.map((image) => ({ url: image, ...(imageAlt ? { alt: imageAlt } : {}) })),
    },
    twitter: {
      // A large card is right for a classified: the photograph is most of
      // what makes somebody open it.
      card: 'summary_large_image',
      title: shareTitle,
      ...(description ? { description } : {}),
      images: resolved,
    },
  };
}

/**
 * A leading slash, no trailing slash, and any query string kept.
 *
 * The query string is deliberately preserved. Almost every canonical here is a
 * bare path, but a numbered page — `/classifieds?page=2` — is canonical to
 * itself, because it holds different advertisements from page one and saying
 * otherwise would claim a hundred advertisements were a duplicate of twelve.
 * An earlier version of this function dropped everything after the `?`, which
 * silently turned every paginated page into a duplicate of page one.
 */
function normalisePath(path: string): string {
  const [rawPath = '/', query] = path.split('?');
  const withSlash = rawPath.startsWith('/') ? rawPath : `/${rawPath}`;
  const trimmed = withSlash.length > 1 ? withSlash.replace(/\/+$/, '') : '/';
  return query ? `${trimmed}?${query}` : trimmed;
}

/**
 * Trims prose to a length a search result will actually show, without cutting
 * a word in half.
 *
 * Roughly 160 characters is what Google renders on a desktop result. Longer is
 * not penalised; it is simply cut with an ellipsis by somebody else, at a
 * point nobody chose.
 */
export function metaDescription(text: string, limit = 160): string {
  const clean = text.replace(/\s+/g, ' ').trim();
  if (clean.length <= limit) return clean;
  const cut = clean.slice(0, limit);
  const lastSpace = cut.lastIndexOf(' ');
  return `${(lastSpace > limit * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[,;:.\s]+$/, '')}…`;
}
